backend:
    name: github
    repo: uequations/news-site-iceberg
    branch: master
    site_domain: https://uequations.com/

publish_mode: editorial_workflow
media_folder: 'static/assets/img'
public_folder: 'assets/img'
show_preview_links: true

collections:
  #Posts (IRS)
  - name: 'posts-irs' # Used in routes, e.g., /admin/collections/blog
    label: 'Posts (IRS)' # Used in the UI
    folder: 'blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'irs.md'
    format: frontmatter
    fields: # The fields for each document, usually in front matter
      - { label: 'URL', name: 'url', widget: 'string'}
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - {
        label: 'Date',
        name: 'date',
        widget: 'datetime',
        format: 'YYYY-MM-DD hh:mm:ss',
      }
      - { label: 'image', name: 'image', widget: 'image' }
      - {
        label: 'Category',
        name: 'category',
        widget: 'select',
        options:
          [
            'Read More',
          ],
      }
      - {
        label: 'Background',
        name: 'background',
        widget: 'select',
        options:
          [
          { label: 'Primary', value: '#9EA4D3' },
          { label: 'Secondary', value: '#380A13' },
          { label: 'Tertiary', value: '#984C16' },
          ],
      }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  #Posts (English)
  - name: 'posts-en' # Used in routes, e.g., /admin/collections/blog
    label: 'Posts (English)' # Used in the UI
    folder: 'blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    extension: 'en.md'
    format: frontmatter
    fields: # The fields for each document, usually in front matter
          - { label: 'URL', name: 'url', widget: 'string'}
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - {
                label: 'Date',
                name: 'date',
                widget: 'datetime',
                format: 'YYYY-MM-DD hh:mm:ss',
            }
          - { label: 'image', name: 'image', widget: 'image' }
          - {
                label: 'Category',
                name: 'category',
                widget: 'select',
                options:
                    [
                        'Markdown',
                        'Javascript',
                        'Images',
                        'Gatsby',
                        'Imagens',
                        'Others',
                        'Outros',
                    ],
            }
          - {
                label: 'Background',
                name: 'background',
                widget: 'select',
                options:
                    [
                        { label: 'Gray', value: '#353b48' },
                        { label: 'Yellow', value: '#e58e26' },
                        { label: 'Green', value: '#079992' },
                        { label: 'Purple', value: '#7d4cdb' },
                        { label: 'Red', value: '#e74c3c' },
                        { label: 'Silver', value: '#bdc3c7' },
                    ],
            }
          - { label: 'Body', name: 'body', widget: 'markdown' }
