// Only one item MUST have the "default: true" key

module.exports = {
  nytimes: {
    path: `nytimes`,
    locale: `en-US`,
    dateFormat: `MM/DD/YYYY`,
    siteLanguage: `en`,
    ogLanguage: `en_US`,
    defaultTitle: `NEW YORK TIMES NEWS | Universal Equations`,
    defaultDescription: `News from various communities, government agencies, and organizations`,
  },
  sba: {
    path: `sba`,
    locale: `en-US`,
    dateFormat: `MM/DD/YYYY`,
    siteLanguage: `en`,
    ogLanguage: `en_US`,
    defaultTitle: `SBA NEWS | Universal Equations`,
    defaultDescription: `News from various communities, government agencies, and organizations`,
  },
  security: {
    path: `security`,
    locale: `en-US`,
    dateFormat: `MM/DD/YYYY`,
    siteLanguage: `en`,
    ogLanguage: `en_US`,
    defaultTitle: `SECURITY NEWS | Universal Equations`,
    defaultDescription: `News from various communities, government agencies, and organizations`,
  },
  treasury: {
    path: `treasury`,
    locale: `en-US`,
    dateFormat: `MM/DD/YYYY`,
    siteLanguage: `en`,
    ogLanguage: `en_US`,
    defaultTitle: `NEW YORK TIMES NEWS | Universal Equations`,
    defaultDescription: `News from various communities, government agencies, and organizations`,
  },
  who: {
    path: `who`,
    locale: `en-US`,
    dateFormat: `MM/DD/YYYY`,
    siteLanguage: `en`,
    ogLanguage: `en_US`,
    defaultTitle: `WORLD HEALTH ORG NEWS | Universal Equations`,
    defaultDescription: `News from various communities, government agencies, and organizations`,
  },
  irs: {
    path: `irs`,
    locale: `en-US`,
    dateFormat: `MM/DD/YYYY`,
    siteLanguage: `en`,
    ogLanguage: `en_US`,
    defaultTitle: `IRS NEWS | Universal Equations`,
    defaultDescription: `The Internal Revenue Service is the nation's tax collection agency and administers the Internal Revenue Code enacted by Congress`,
  },
  index: {
    default: true,
    path: `index`,
    locale: `en-US`,
    dateFormat: `MM/DD/YYYY`,
    siteLanguage: `en`,
    ogLanguage: `en_US`,
    defaultTitle: `COMMUNITY & GOVERNMENT NEWS | Universal Equations`,
    defaultDescription: `From Universal Equations, community and government news from around thw world`,
  },
}
